import {mkdir, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {buildAiSchema, buildLocalSchema, toJsonSchema} from './storyboard.ts';
import {capabilityPackageSchema} from './capability.ts';
import {settingsJsonSchema} from './settings.ts';
import {videoProjectSchema} from './project.ts';

export * from './storyboard.ts';
export * from './settings.ts';
export * from './project.ts';
export * from './transitions.ts';
export * from './scenegraph.ts';
export * from './capability.ts';
export * from './verified-index.ts';
export {validateStoryboardDetailed, validateBoardV2} from './storyboard-validation.ts';
export type {ValidationContext, StoryboardDiagnostic, StoryboardValidation} from './storyboard-validation.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));

/** No destination preserves the App's historical AI schema export. A directory
 * exports the standalone schema set without writing application configuration. */
export async function exportContracts(destination?: string): Promise<void> {
  const generated = buildAiSchema();
  const {$schema, ...body} = generated;
  const output = {$schema, $comment: 'generated by contracts export; do not edit', ...body};
  const directory = destination ?? path.resolve(HERE, '../config');
  await mkdir(directory, {recursive: true});
  const schemas = destination ? {
    'storyboard.schema.json': output,
    'storyboard-local.schema.json': buildLocalSchema(),
    'capability.schema.json': toJsonSchema(capabilityPackageSchema),
    'settings.schema.json': settingsJsonSchema,
    'project.schema.json': toJsonSchema(videoProjectSchema)
  } : {'storyboard.schema.json': output};
  for (const [name, schema] of Object.entries(schemas)) {
    await writeFile(path.join(directory, name), `${JSON.stringify(schema, null, 2)}\n`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args[0] !== '--export' || args.length > 2) throw new Error('Usage: node contracts/index.ts --export [directory]');
  await exportContracts(args[1]);
}
